const SCALE_1_TO_5 = ["1", "2", "3", "4", "5"];
const ROOM_DURATION = ["Trop long", "Un peu long", "Bien comme il faut", "Rapide & fluide"];

export function getFormtestPageData() {
  return {
    title: "Marée Noire — Test SIGNAL",
    headerTitle: "THE ROOM",
    headerSubtitle: "Give Me The Pitch × Marée Noire Session 01",
    eyebrow: "The Room × GMTP",
    session: "Session 01",
    intro:
      "Tu viens de traverser Marée Noire. Ce test capte maintenant ton signal : ce qui accroche, ce qui inquiète, ce qui donne envie de continuer et ce qui resterait à pousser.",
    legalNote:
      "Vos réponses sont anonymes et utilisées uniquement dans le cadre du développement de la série.",
    submitLabel: "SUBMIT",
    processingLogo: "Give Me The Pitch",
    processingMessages: [
      "Anonymisation en cours...",
      "Consolidation du panel...",
      "Analyse des dimensions...",
      "Scoring en cours...",
      "",
    ],
    confirmSignal: "un signal a été créé",
    confirmTitle: "Merci",
    confirmSubtext: "ideas begin with you",
    sections: [
      {
        id: "hook",
        title: "Hook",
        description: "L'accroche immédiate : promesse, curiosité, envie d'aller plus loin.",
        questions: [
          {
            name: "reaction",
            label: "Après les 10 premières secondes de lecture, quelle a été votre réaction immédiate ?",
            type: "radio",
            required: true,
            options: ["Je veux voir ça", "Je suis curieux·se", "Bof", "Pas pour moi"],
          },
          {
            name: "clarte",
            label: "La promesse du projet me paraît claire",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "curiosite",
            label: "Ça me donne envie d'en savoir plus",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "envie_regarder",
            label: "J'ai envie de regarder ce projet",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "accroche",
            label: "Ce qui m'accroche là, tout de suite :",
            type: "textarea",
            required: true,
            placeholder: "Quelques mots…",
          },
        ],
      },
      {
        id: "feel",
        title: "Feel",
        description: "Clarté émotionnelle, intensité et sensation dominante.",
        questions: [
          {
            name: "clarte_univers",
            label: "L'univers de la série me paraît clair",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "clarte_dramatique",
            label: "Les enjeux dramatiques me paraissent clairs",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "clarte_emotionnel",
            label: "Les enjeux émotionnels me paraissent clairs",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "intensite",
            label: "Intensité émotionnelle",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "emotion",
            label: "Émotion dominante ressentie",
            type: "radio",
            required: true,
            options: ["Tension", "Curiosité", "Joie", "Peur", "Tristesse", "Malaise", "Autre"],
          },
          {
            name: "emotionAutre",
            label: "Si autre, précisez",
            type: "text",
            placeholder: "Précisez…",
            visibleWhen: { name: "emotion", value: "Autre" },
          },
          {
            name: "feel_verbatim",
            label: "Ça me donne envie parce que je m'attends à ressentir :",
            type: "textarea",
            required: true,
            placeholder: "Quelques mots…",
          },
        ],
      },
      {
        id: "care",
        title: "Care",
        description: "Attachement, projection et relation aux personnages.",
        questions: [
          {
            name: "interet_perso",
            label: "Les personnages suscitent mon intérêt",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "projection_perso",
            label: "Je me projette avec au moins un personnage",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "attachement",
            label: "Y a-t-il un personnage que vous appréciez plus que les autres ?",
            type: "radio",
            required: true,
            options: ["Oui", "Non"],
          },
          {
            name: "care_perso",
            label: "Lequel ou laquelle ?",
            type: "checkbox",
            options: ["Iroise", "Vera", "Vikram", "Soaz", "Camille", "Noé", "Le Braz", "Lenn"],
          },
          {
            name: "care_pourquoi",
            label: "Pourquoi ?",
            type: "textarea",
            placeholder: "Complexité psychologique, moteur intéressant, je me sens proche de…",
          },
        ],
      },
      {
        id: "continue",
        title: "Continue",
        description: "Ce qui pousse à continuer, ce qui peut faire décrocher.",
        questions: [
          {
            name: "questions",
            label: "Les questions soulevées me donnent envie de voir la suite",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "continue_raison",
            label: "Ce qui me donnerait envie de continuer :",
            type: "checkbox",
            options: ["Les personnages", "Le mystère", "L'univers", "Le ton", "Le concept", "L'émotion", "Autre"],
          },
          {
            name: "decroche",
            label: "Ce qui pourrait me faire décrocher :",
            type: "checkbox",
            options: [
              "Pas clair",
              "Trop lent",
              "Trop vu",
              "Personnages pas attachants",
              "Pas crédible",
              "Pas mon genre",
              "Trop dark",
              "Autre",
            ],
          },
          {
            name: "binge",
            label: "Ce qui me ferait binge-watcher :",
            type: "textarea",
            required: true,
            placeholder: "Quelques mots…",
          },
          {
            name: "drop",
            label: "Ce qui me ferait décrocher :",
            type: "textarea",
            required: true,
            placeholder: "Quelques mots…",
          },
        ],
      },
      {
        id: "share",
        title: "Share",
        description: "Recommandation, conversation et transmission du projet.",
        questions: [
          {
            name: "reco",
            label: "Recommanderiez-vous ce projet à votre entourage ?",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "conversation",
            label: "J'en parlerais spontanément autour de moi",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "cible",
            label: "À qui le recommanderiez-vous en priorité ?",
            type: "checkbox",
            options: ["Ami·e fan du genre", "Mon·ma partenaire", "Mes collègues", "Personne", "Je sais pas encore", "Autre"],
          },
          {
            name: "pitch_mots",
            label: "Si vous deviez donner envie à quelqu'un de regarder, vous diriez ?",
            type: "text",
            required: true,
            placeholder: "Des mots-clés suffisent…",
          },
        ],
      },
      {
        id: "the-room",
        title: "The Room",
        description: "Le dispositif de lecture lui-même : clarté, durée, utilité et expérience.",
        questions: [
          {
            name: "room_lecture",
            label: "Ressenti sur la lecture du projet",
            type: "radio",
            required: true,
            options: ROOM_DURATION,
          },
          {
            name: "room_suffisant",
            label: "Les éléments partagés vous ont-ils semblé suffisants pour juger le projet ?",
            type: "radio",
            required: true,
            options: ["Oui", "Non"],
          },
          {
            name: "room_plus",
            label: "Si non, qu'auriez-vous aimé lire ou voir en plus ?",
            type: "textarea",
            placeholder: "Vos suggestions…",
            visibleWhen: { name: "room_suffisant", value: "Non" },
          },
          {
            name: "room_utilite",
            label: "Ce format de panel me semble utile pour développer un projet",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "room_xp",
            label: "J'ai apprécié l'expérience",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
          {
            name: "room_duree",
            label: "Ressenti sur la durée et la fluidité du formulaire",
            type: "radio",
            required: true,
            options: ROOM_DURATION,
          },
          {
            name: "room_reco",
            label: "Recommanderiez-vous THE ROOM ?",
            type: "radio",
            required: true,
            options: SCALE_1_TO_5,
          },
        ],
      },
    ],
  };
}
